name: Test Prediction Run

on:
  workflow_dispatch: # これを入れることで、GitHubの画面から手動で実行ボタンが押せるようになります

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests Pillow  # visualizerが必要とするライブラリを並べてください

      - name: Run Test Script
        env:
          # GitHubのSettings > Secretsで設定した名前と一致させる
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python test.py
